# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  compile-plug:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          path: ./plug

      - name: Clone Silverbullet
        uses: actions/checkout@v4
        with:
          repository: silverbulletmd/silverbullet
          path: ./silverbullet

      - name: Install Deno
        uses: denoland/setup-deno@v2

      - name: Compile Silverbullet
        run: |
          deno task build
          deno task install
        working-directory: ./silverbullet

      - name: Compile Plug
        run: deno task build
        working-directory: ./plug

      - name: Push back results
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "github-actions[bot]"
          author_email: "41898282+github-actions[bot]@users.noreply.github.com"
          cwd: ./plug
          message: "Automated plug compliation"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
